openapi: 3.0.0
info:
  title: VerseguY Master Server Admin APIs
  version: 0.1.0
paths:
  /admin/keys:
    get:
      summary: Get master key info
      description: Returns whether a master key is configured and the base64 public key.
      responses:
        '200':
          description: Key info
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
                  public_key_b64:
                    type: string
                  path:
                    type: string
        '404':
          description: No master key configured
  /admin/keys/rotate:
    post:
      summary: Rotate master signing key
      description: Rotates the server master key; requires admin token header `x-admin-token`.
      parameters:
        - in: header
          name: x-admin-token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: New public key
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  public_key_b64:
                    type: string
        '403':
          description: Admin token invalid or admin disabled
  /admin/keys/import:
    post:
      summary: Import master key
      description: Import a new keypair as base64 encoded 64 bytes JSON body: {"key_b64": "..."}. Requires admin token header `x-admin-token`.
      parameters:
        - in: header
          name: x-admin-token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key_b64:
                  type: string
      responses:
        '200':
          description: Imported public key
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  public_key_b64:
                    type: string
        '400':
          description: Bad request (invalid key)
        '403':
          description: Admin token invalid or admin disabled
